<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduApoyos.Application\EduApoyos.Application.csproj" />
    <ProjectReference Include="..\EduApoyos.Infrastructure\EduApoyos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
